#!/bin/sh

if uci -q get system.@system[0] >/dev/null; then
	uci -q set system.@system[0].zonename='Asia/Shanghai'
	uci -q set system.@system[0].timezone='CST-8'
	uci -q set system.@system[0].conloglevel='4'
	uci -q set system.@system[0].cronloglevel='8'
	uci -q set system.@system[0].ttylogin='1'
	uci -q del system.ntp.server
	uci -q add_list system.ntp.server='ntp.aliyun.com'
	uci -q add_list system.ntp.server='0.openwrt.pool.ntp.org'
	uci commit system
fi

exit 0
